export const ENV_KEY = {
  PCA_BASE_URL: 'PCA_BASE_URL',
  PCA_USERNAME: 'PCA_USERNAME',
  PCA_PASSWORD: 'PCA_PASSWORD',

  // TELEGRAM
  TELEGRAM_BASE_URL: 'TELEGRAM_BASE_URL',
  TELEGRAM_BOT_TOKEN: 'TELEGRAM_BOT_TOKEN',
  TELEGRAM_CHAT_ID: 'TELEGRAM_CHAT_ID',

  // MONGODB
  MONGO_URI: 'MONGO_URI',

  // CLOUDSTORAGE
  STORAGE_PROVIDER: 'STORAGE_PROVIDER',
};

export const CLOUDSTORAGE = {
  DROPBOX: 'dropbox',
};
