export const ENV_KEY = {
  PCA_BASE_URL: 'PCA_BASE_URL',
  PCA_USERNAME: 'PCA_USERNAME',
  PCA_PASSWORD: 'PCA_PASSWORD',

  // TELEGRAM
  TELEGRAM_BASE_URL: 'TELEGRAM_BASE_URL',
  TELEGRAM_BOT_TOKEN: 'TELEGRAM_BOT_TOKEN',
  TELEGRAM_CHAT_ID: 'TELEGRAM_CHAT_ID',

  // MONGODB
  MONGO_URI: 'MONGO_URI',

  // CLOUDSTORAGE
  STORAGE_PROVIDER: 'STORAGE_PROVIDER',
  DROPBOX_ACCESS_TOKEN: 'DROPBOX_ACCESS_TOKEN',

  // RABBITMQ
  RABBITMQ_CONN: 'RABBITMQ_CONN',
};

export const CLOUDSTORAGE = {
  DROPBOX: 'dropbox',
};

export const QUEUE_NAME = {
  EMAIL_QUEUE: 'email_queue',
  UPLOAD_QUEUE: 'upload_queue',
  IMAGE_QUEUE: 'image_queue',
};

export const MICROSERVICE_MESSAGE_PATTERNS = {
  IMAGE: {
    IMAGE_UPLOADED: 'image-uploaded',
    IMAGE_PROCESSED: 'image-processed',
  },
};
